package manifests

import (
	"bytes"
	"encoding/json"
	"fmt"

	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/api/resource"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	kueuev1beta1 "sigs.k8s.io/kueue/apis/kueue/v1beta1"
	"sigs.k8s.io/yaml"
)

const (
	topologyName  = "gpu-topology"
	defaultNS     = "default"
	sharedCohort  = "shared-gpu"
	gpuNodeLabel  = "infra.example.io/gpu-node"
	rackNodeLabel = "infra.example.io/rack"
	gpuResource   = corev1.ResourceName("example.com/gpu")
)

type queueConfig struct {
	name        string
	cpuQuota    string
	memoryQuota string
	gpuQuota    string
}

var queueConfigs = []queueConfig{
	{name: "training", cpuQuota: "80", memoryQuota: "80Gi", gpuQuota: "10"},
	{name: "batch", cpuQuota: "20", memoryQuota: "20Gi", gpuQuota: "2"},
}

// RenderKueueResources renders the Kueue configuration owned by this project.
func RenderKueueResources() ([]byte, error) {
	var output bytes.Buffer
	output.WriteString("# Code generated by go run ./cmd/manifestgen; DO NOT EDIT.\n")
	output.WriteString("# yaml-language-server: $schema=./schemas/kueue-v1beta1.schema.json\n")

	for index, object := range kueueResources() {
		if index > 0 {
			output.WriteString("---\n")
		}
		encoded, err := marshalResource(object)
		if err != nil {
			return nil, fmt.Errorf("marshal Kueue resource %d: %w", index, err)
		}
		output.Write(encoded)
	}
	return output.Bytes(), nil
}

func marshalResource(object any) ([]byte, error) {
	encoded, err := json.Marshal(object)
	if err != nil {
		return nil, err
	}
	var fields map[string]json.RawMessage
	if err := json.Unmarshal(encoded, &fields); err != nil {
		return nil, err
	}
	delete(fields, "status")
	encoded, err = json.Marshal(fields)
	if err != nil {
		return nil, err
	}
	return yaml.JSONToYAML(encoded)
}

func kueueResources() []any {
	apiVersion := kueuev1beta1.GroupVersion.String()
	resources := []any{topology(apiVersion), resourceFlavor(apiVersion)}
	for _, config := range queueConfigs {
		resources = append(resources, clusterQueue(apiVersion, config), localQueue(apiVersion, config))
	}
	return resources
}

func topology(apiVersion string) *kueuev1beta1.Topology {
	return &kueuev1beta1.Topology{
		TypeMeta:   metav1.TypeMeta{APIVersion: apiVersion, Kind: "Topology"},
		ObjectMeta: metav1.ObjectMeta{Name: topologyName},
		Spec: kueuev1beta1.TopologySpec{Levels: []kueuev1beta1.TopologyLevel{
			{NodeLabel: rackNodeLabel},
			{NodeLabel: corev1.LabelHostname},
		}},
	}
}

func resourceFlavor(apiVersion string) *kueuev1beta1.ResourceFlavor {
	topologyReference := kueuev1beta1.TopologyReference(topologyName)
	return &kueuev1beta1.ResourceFlavor{
		TypeMeta:   metav1.TypeMeta{APIVersion: apiVersion, Kind: "ResourceFlavor"},
		ObjectMeta: metav1.ObjectMeta{Name: topologyName},
		Spec: kueuev1beta1.ResourceFlavorSpec{
			NodeLabels:   map[string]string{gpuNodeLabel: "true"},
			TopologyName: &topologyReference,
		},
	}
}

func clusterQueue(apiVersion string, config queueConfig) *kueuev1beta1.ClusterQueue {
	return &kueuev1beta1.ClusterQueue{
		TypeMeta:   metav1.TypeMeta{APIVersion: apiVersion, Kind: "ClusterQueue"},
		ObjectMeta: metav1.ObjectMeta{Name: config.name},
		Spec: kueuev1beta1.ClusterQueueSpec{
			Cohort:            kueuev1beta1.CohortReference(sharedCohort),
			NamespaceSelector: &metav1.LabelSelector{},
			ResourceGroups: []kueuev1beta1.ResourceGroup{{
				CoveredResources: []corev1.ResourceName{
					corev1.ResourceCPU,
					corev1.ResourceMemory,
					gpuResource,
				},
				Flavors: []kueuev1beta1.FlavorQuotas{{
					Name: kueuev1beta1.ResourceFlavorReference(topologyName),
					Resources: []kueuev1beta1.ResourceQuota{
						{Name: corev1.ResourceCPU, NominalQuota: resource.MustParse(config.cpuQuota)},
						{Name: corev1.ResourceMemory, NominalQuota: resource.MustParse(config.memoryQuota)},
						{Name: gpuResource, NominalQuota: resource.MustParse(config.gpuQuota)},
					},
				}},
			}},
		},
	}
}

func localQueue(apiVersion string, config queueConfig) *kueuev1beta1.LocalQueue {
	return &kueuev1beta1.LocalQueue{
		TypeMeta: metav1.TypeMeta{APIVersion: apiVersion, Kind: "LocalQueue"},
		ObjectMeta: metav1.ObjectMeta{
			Name:      config.name,
			Namespace: defaultNS,
		},
		Spec: kueuev1beta1.LocalQueueSpec{
			ClusterQueue: kueuev1beta1.ClusterQueueReference(config.name),
		},
	}
}
