# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.34.1-standalone-strict/all.json
apiVersion: v1
kind: ConfigMap
metadata:
  name: ai-scheduler-config
  namespace: ai-infra-system
data:
  config.yaml: |
    apiVersion: kubescheduler.config.k8s.io/v1
    kind: KubeSchedulerConfiguration
    clientConnection:
      kubeconfig: ""
    leaderElection:
      leaderElect: false
    profiles:
      - schedulerName: ai-scheduler
        plugins:
          preFilter:
            enabled:
              - name: GPUTopology
          filter:
            enabled:
              - name: GPUTopology
          preScore:
            enabled:
              - name: GPUTopology
          score:
            disabled:
              - name: "*"
            enabled:
              - name: NodeResourcesFit
                weight: 10
              - name: GPUTopology
                weight: 5
        pluginConfig:
          - name: NodeResourcesFit
            args:
              scoringStrategy:
                type: MostAllocated
                resources:
                  - name: example.com/gpu
                    weight: 1
