# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.34.1-standalone-strict/all.json
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aijob-controller
  namespace: ai-infra-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aijob-controller
  template:
    metadata:
      labels:
        app: aijob-controller
    spec:
      serviceAccountName: aijob-controller
      containers:
        - name: controller
          image: ai-infra-lab:dev
          imagePullPolicy: IfNotPresent
          command: ["/controller"]
          ports:
            - name: metrics
              containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: aijob-controller-metrics
  namespace: ai-infra-system
spec:
  selector:
    app: aijob-controller
  ports:
    - name: metrics
      port: 8080
      targetPort: metrics
