---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: aijob-controller
rules:
- apiGroups:
  - infra.example.io
  resources:
  - aijobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - infra.example.io
  resources:
  - aijobs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - jobset.x-k8s.io
  resources:
  - jobsets
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kueue.x-k8s.io
  resources:
  - localqueues
  verbs:
  - get
  - list
  - watch
