apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/kubernetes-sigs/kueue/releases/download/v0.14.3/manifests.yaml
patches:
  - path: controller-manager-patch.yaml
